package com.example.tp_poo.models;

public enum Categories {
 STRUCTUREFAMILIALE,
    DYNAMIQUEFAMILIALE,
    ANTECEDENTS_FAMILIAUX,
    CONDITIONS_NATALES,
    DEVELOPPEMENT_PSYCHOMOTEUR,
    DEVELOPPEMENT_LANGAGIER,
    CARACTERE,
    COMPORTEMENT
}
